export default function TermsPage() {
  return (
    <main className="flex-1 py-12 px-4 TermsPage" style={{ background: "var(--background)" }}>
      <div className="max-w-2xl mx-auto space-y-8">
        <h1 style={{ fontSize: "40px", color: "var(--foreground)" }}>
          Terms &amp; Conditions
        </h1>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>1. Acceptance of Terms</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            By accessing and using Dummy Content ("the Service"), you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>2. Use of the Service</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            Dummy Content provides tools to generate placeholder images, text, and embeddable iframes for development and design purposes. The Service is provided free of charge and is intended solely for lawful use. You agree not to use the Service for any illegal or unauthorized purpose.
          </p>
        </section>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>3. Intellectual Property</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            All content generated by the Service is provided as-is for placeholder use only. The Service itself, including its design, code, and branding, is the property of Dummy Content and may not be reproduced without permission.
          </p>
        </section>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>4. Disclaimer of Warranties</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            The Service is provided "as is" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components.
          </p>
        </section>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>5. Limitation of Liability</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            To the fullest extent permitted by law, Dummy Content shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>6. Changes to Terms</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            We reserve the right to update these Terms and Conditions at any time. Continued use of the Service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 style={{ fontSize: "1.125rem", fontWeight: 600, color: "var(--foreground)" }}>7. Contact</h2>
          <p style={{ fontSize: "0.9rem", color: "var(--muted)", lineHeight: 1.7 }}>
            If you have any questions about these Terms and Conditions, please contact us at{" "}
            <a href="mailto:hello@dummycontent.app" style={{ color: "var(--accent)" }}>
              hello@dummycontent.app
            </a>.
          </p>
        </section>

        <p style={{ fontSize: "0.75rem", color: "var(--muted)" }}>
          Last updated: April 2026
        </p>
      </div>
    </main>
  );
}
