import type { Lang } from "@/lib/i18n/translations";

export interface TermsCopy {
  title: string;
  metaDescription: string;
  sections: { heading: string; body: string }[];
  contactHeading: string;
  /** Texto anterior al mail de contacto; el mail se renderiza como enlace. */
  contactBody: string;
  lastUpdated: string;
}

export const CONTACT_EMAIL = "hello@dummycontent.app";

export const TERMS_CONTENT: Record<Lang, TermsCopy> = {
  en: {
    title: "Terms & Conditions",
    metaDescription:
      "Terms and Conditions for using Dummy Content — free placeholder tools for development and design.",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: 'By accessing and using Dummy Content ("the Service"), you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.',
      },
      {
        heading: "2. Use of the Service",
        body: "Dummy Content provides tools to generate placeholder images, text, and embeddable iframes for development and design purposes. The Service is provided free of charge and is intended solely for lawful use. You agree not to use the Service for any illegal or unauthorized purpose.",
      },
      {
        heading: "3. Intellectual Property",
        body: "All content generated by the Service is provided as-is for placeholder use only. The Service itself, including its design, code, and branding, is the property of Dummy Content and may not be reproduced without permission.",
      },
      {
        heading: "4. Disclaimer of Warranties",
        body: 'The Service is provided "as is" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components.',
      },
      {
        heading: "5. Limitation of Liability",
        body: "To the fullest extent permitted by law, Dummy Content shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.",
      },
      {
        heading: "6. Changes to Terms",
        body: "We reserve the right to update these Terms and Conditions at any time. Continued use of the Service after changes constitutes acceptance of the new terms.",
      },
    ],
    contactHeading: "7. Contact",
    contactBody: "If you have any questions about these Terms and Conditions, please contact us at",
    lastUpdated: "Last updated: April 2026",
  },
  es: {
    title: "Términos y Condiciones",
    metaDescription:
      "Términos y Condiciones de uso de Dummy Content — herramientas gratuitas de contenido de relleno para desarrollo y diseño.",
    sections: [
      {
        heading: "1. Aceptación de los términos",
        body: 'Al acceder y utilizar Dummy Content ("el Servicio"), aceptás quedar obligado por estos Términos y Condiciones. Si no estás de acuerdo con ellos, por favor no uses el Servicio.',
      },
      {
        heading: "2. Uso del Servicio",
        body: "Dummy Content ofrece herramientas para generar imágenes, texto e iframes embebibles de relleno con fines de desarrollo y diseño. El Servicio se presta de forma gratuita y está destinado exclusivamente a un uso lícito. Te comprometés a no utilizarlo con ningún fin ilegal o no autorizado.",
      },
      {
        heading: "3. Propiedad intelectual",
        body: "Todo el contenido generado por el Servicio se entrega tal cual, únicamente para uso como contenido de relleno. El Servicio en sí mismo, incluyendo su diseño, su código y su marca, es propiedad de Dummy Content y no puede reproducirse sin autorización.",
      },
      {
        heading: "4. Exclusión de garantías",
        body: 'El Servicio se ofrece "tal cual", sin garantías de ningún tipo, ni expresas ni implícitas. No garantizamos que el Servicio vaya a funcionar de forma ininterrumpida, libre de errores o libre de componentes dañinos.',
      },
      {
        heading: "5. Limitación de responsabilidad",
        body: "En la máxima medida permitida por la ley, Dummy Content no será responsable por daños indirectos, incidentales, especiales o consecuentes derivados del uso del Servicio.",
      },
      {
        heading: "6. Cambios en los términos",
        body: "Nos reservamos el derecho de actualizar estos Términos y Condiciones en cualquier momento. El uso continuado del Servicio después de un cambio implica la aceptación de los nuevos términos.",
      },
    ],
    contactHeading: "7. Contacto",
    contactBody: "Si tenés alguna consulta sobre estos Términos y Condiciones, escribinos a",
    lastUpdated: "Última actualización: abril de 2026",
  },
};
